name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: psf/black@stable
      uses: actions/setup-python@v2
      - run: pip install black
      - run: black .
      - run: git push